### PR TITLE
eclipse-jdt updates and other generic fixes

### PR DESCRIPTION
**Pull request by ajayk**

### CODE REVIEW

**Comment by ajayk** [comment]
i didn't see this  https://github.com/takari/takari-lifecycle/pull/103/

**Comment by jvanzyl** [comment]
I didn't see either of them, my notifications aren't setup very well. Do you want me to look at both of them together? @cstamas feel free to merge everything in, happy to give you access.

**Comment by ajayk** [comment]
@cstamas feel free to cherry pick the changes or close the #104

**Comment by cstamas** [comment]
@jvanzyl this PR requires parent changes https://github.com/takari/takari-pom/pull/9 and those need a release before this PR can carry on...

**Comment by cstamas** [comment]
> @cstamas feel free to cherry pick the changes or close the #104

Let's merge #103 and then cherry pick whatever needed from here...

**Comment by jvanzyl** [comment]
Feel free to merge this if it looks good.

**Comment by cstamas** [comment]
Superseded by https://github.com/takari/takari-lifecycle/pull/105 (has both PRs merged)

**Pull request closed without merging**
