### PR TITLE
Maven source encoding support for resource filtering

### PR DESCRIPTION
**Pull request by cyberwasp**
This commit taking maven property "project.build.sourceEncoding" into account when reading and writing resources.  If java "file.encoding" property is not UTF-8 (in my case win1251) and real resource file encoding is UTF-8 then some chars can read as Unicode Character 'REPLACEMENT CHARACTER' (U+FFFD). This will lead to char distortion in filter output.

### CODE REVIEW

**Comment by jvanzyl** [comment]
Tried to merge this but it causes the tests to fail. Did you run the tests?

**Comment by ifedorenko** [comment]
Also, the new test is incomplete. All systems we use to build/release takari lifecycle use UTF-8 by default, which means the test will not actually attempt to do any encoding conversion. To avoid possible collision with local encoding I suggest using iso 8859-5, nobody uses that by default ;-)

**Comment by cyberwasp** [comment]
Sorry. Silly optimization for already tested code without run test again.

**Comment by ifedorenko** [comment]
-1

* don't use wildcard imports
* need to fix unit test to actually test on the systems that use UTF-8 by default
* need to squash into single commit

**Comment by jvanzyl** [comment]
I'll wait a day if you want to try and fix this up. I'd like to cut a release tomorrow if possible.

**Comment by cyberwasp** [comment]
If default encoding UTF-8 all will be good as before. Problem appear when default encoding is not UTF-8, but real source encoding is UTF-8

**Comment by ifedorenko** [comment]
+1 

I missed `-Dfile.encoding=windows-1251` in the test, sorry.

**Comment by jvanzyl** [comment]
Merged, thanks!

**Pull request closed without merging**
