### PR TITLE
Add compiler support to generate method parameters attribute

### LINKED ISSUE #25: Please document how to pass compiler args
I need to configure java 8 parameters:

```xml
    <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.3</version>
        <configuration>
            <compilerArgs>
                <arg>-parameters</arg>
            </compilerArgs>
        </configuration>
    </plugin>
```

http://blog.javabien.net/2014/04/24/get-parameter-names-in-java-8/

### PR DESCRIPTION
**Pull request by mariuszs**
Fixes #25

### CODE REVIEW

**Comment by ifedorenko** [comment]
Please update the pull request to include automated test(s). I imaging one test could build a small project with <parameters>=true and assert the expected files are generated during the build. Test(s) for regeneration of the files during incremental build will also be useful.

**Comment by ifedorenko** [comment]
Forgot to mention, you will also need to sign [Takari CLA](http://takari.io/support/TakariCLA.pdf) before we can accept this pull request (@jvanzyl please correct me if I am wrong)

**Comment by mariuszs** [comment]
I have some problems with asm and jdt, so the test for jdt is ignored (in very ugly way). 

Please take a look.

**Comment by mariuszs** [comment]
Takari CLA signed.

**Comment by mariuszs** [comment]
problem with jdt fixed, I think PR is complete

**Comment by ifedorenko** [comment]
Sorry to be a pain, but couple of comments/suggestions

* the test needs to assume `isJava8orBetter || CompilerJdt.ID.equals(compilerId)`, otherwise it fails when run with java 7.
* the test does not need pom.xml file, the pom is redundant and only adds noise to the sources

**Comment by mariuszs** [comment]
Thanks for suggestions :) Fixed

**Comment by ifedorenko** [comment]
+1

**Comment by jvanzyl** [comment]
Merged. Thanks!

**Pull request closed without merging**
