### PR TITLE
Use authentication with altDeploymentRepository

### PR DESCRIPTION
**Pull request by dfelliott**
Allows use of settings.xml server authentication with -DaltDeploymentRepository

### CODE REVIEW

**Comment by ifedorenko** [comment]
The patch looks reasonable but I think we need a regression test. 

I also believe Takari requires signed [CLA](http://takari.io/support/TakariCLA.pdf) before accepting any patches.

**Comment by MadhuVK** [comment]
Has this change already been integrated with another PR? One of my projects (on version 1.11) might be failing due to this issue.

**Comment by ifedorenko** [comment]
No, wasn't merged, I can't accept changes without signed CLA on file.

**Comment by dfelliott** [comment]
This code is present in at least 3 places in Maven/Aether already:

* aether-core/aether-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositorySystem.java
* maven/maven-compat/src/main/java/org/apache/maven/artifact/deployer/DefaultArtifactDeployer.java
* aether-ant/src/main/java/org/eclipse/aether/internal/ant/ConverterUtils.java

**Pull request closed without merging**
