### PR TITLE
Update plugin build and dependencies

### PR DESCRIPTION
**Pull request by cstamas**
Depends on https://github.com/takari/takari-pom/pull/9

High level changes:
- updated wrapper to latest
- uses parent v 50
- remove/adjust prerequisites (needed only for plugin, parent POM not, etc)
- get rid of animal sniffer as compiler use `release` flag
- update plugin dependencies
- update sources where depedendency introduced change
- one IT changed: CompileAnnotationProcessingTest as it used source 1.6, that is unsupported by Java 17. Changed to `release 7`
- update github workflow with distribution
- styfle/cancel-workflow-action: bump

With these changes the build works okay on Java 17 as well.

### CODE REVIEW

**Comment by ajayk** [comment]
@jvanzyl SNAPSHOT needs to be released io.takari:takari:pom:50-SNAPSHOT

**Comment by cstamas** [comment]
@ajayk asked for permission to deploy, once got, will do releases... Am currently fixing plugin IT framework that fail with mvn 3.8.6...

**Comment by cstamas** [comment]
Parent 50 released, needs some time to sync to Maven Central, then we can continue.... @ajayk

**Comment by cstamas** [comment]
IT framework failure reson w/ mvn 3.8.4+ is this commit:
https://github.com/apache/maven/commit/05b748ff6aa15aa63a9c9d5f9f5679f47bf9e83d

The change in DefaultMojoExecutionConfigurator.java causes NPE, as `mojoExecution.getPlugin()` when created by IT framework is `null`.

**Comment by cstamas** [comment]
Also, I'd make this 2.1.0 instead 2.0.10... wdyt? @ajayk

**Comment by ajayk** [comment]
@

> Also, I'd make this 2.1.0 instead 2.0.10... wdyt? @ajayk

sounds good @cstamas

**Review by ajayk — APPROVED** [review]

**Pull request merged**
